from __future__ import annotations

from typing import Any, Protocol

from flame_memory.models import FlamePoolState, MemoryItem, PoolItem, ReflectionBatchRun


class FlameStore(Protocol):
    root: Any

    def load_agent(self, agent_id: str) -> Any: ...
    def list_self_learning_agents(self) -> list[Any]: ...
    def save_memory(self, memory: MemoryItem) -> None: ...
    def save_memory_vector(self, agent_id: str, memory_id: str, embedding: list[float]) -> None: ...
    def query_memory_vectors(self, agent_id: str, query_embedding: list[float], limit: int = 5) -> list[tuple[str, float]]: ...
    def load_memory(self, agent_id: str, memory_id: str) -> MemoryItem: ...
    def list_memories(self, agent_id: str) -> list[MemoryItem]: ...
    def load_events(self, session_id: str) -> list[Any]: ...
    def save_flame_pool_item(self, item: PoolItem) -> None: ...
    def list_flame_pool_items(self, agent_id: str | None = None, state: FlamePoolState | None = None) -> list[PoolItem]: ...
    def delete_flame_pool_items(self, pool_item_ids: list[str]) -> None: ...
    def save_flame_run(self, run: ReflectionBatchRun) -> None: ...
    def list_flame_runs(self, agent_id: str | None = None) -> list[ReflectionBatchRun]: ...
