from flame_memory.manager import (
    FLAME_EXTRACTION_PROMPT_VERSION,
    FLAME_EXTRACTION_SYSTEM_PROMPT,
    FLAME_REFLECTION_PROMPT_VERSION,
    FLAME_REFLECTION_SYSTEM_PROMPT,
    FLAME_REFLECTION_CONTENT_MAX_CHARS,
    FLAME_TEMP_CONTENT_MAX_CHARS,
    FlameManager,
    utc_now,
)

__all__ = [
    "FLAME_EXTRACTION_PROMPT_VERSION",
    "FLAME_EXTRACTION_SYSTEM_PROMPT",
    "FLAME_REFLECTION_PROMPT_VERSION",
    "FLAME_REFLECTION_SYSTEM_PROMPT",
    "FLAME_REFLECTION_CONTENT_MAX_CHARS",
    "FLAME_TEMP_CONTENT_MAX_CHARS",
    "FlameManager",
    "utc_now",
]
