from __future__ import annotations

from enum import StrEnum
from typing import Any, Protocol

from agent_os.protocol import (
    AgentDefinition,
    GateDecisionReport,
    LearningCandidate,
    LearningRun,
    MemoryItem,
    PromotionPolicy,
    PromotionState,
    RollbackRecord,
    Session,
    SessionEvent,
    SessionStatus,
    SkillDefinition,
    ToolAuditEvent,
    ToolManifest,
    ValidationReport,
)


class StorageMode(StrEnum):
    LOCAL = "local"
    DUAL_WRITE = "dual_write"
    POSTGRES_REDIS = "postgres_redis"


class DomainStore(Protocol):
    root: Any

    def init(self) -> None: ...
    def save_agent(self, agent: AgentDefinition) -> None: ...
    def load_agent(self, agent_id: str) -> AgentDefinition: ...
    def list_agents(self) -> list[AgentDefinition]: ...
    def save_memory(self, memory: MemoryItem) -> None: ...
    def load_memory(self, agent_id: str, memory_id: str) -> MemoryItem: ...
    def list_memories(self, agent_id: str) -> list[MemoryItem]: ...
    def save_skill(self, skill: SkillDefinition) -> None: ...
    def load_skill(self, skill_id: str) -> SkillDefinition: ...
    def list_skills(self) -> list[SkillDefinition]: ...
    def bind_skill(self, agent_id: str, skill_id: str) -> None: ...
    def list_bound_skill_ids(self, agent_id: str) -> list[str]: ...
    def save_tool_manifest(self, manifest: ToolManifest) -> None: ...
    def load_tool_manifest(self, tool_id: str) -> ToolManifest: ...
    def list_tool_manifests(self) -> list[ToolManifest]: ...
    def bind_tool(self, agent_id: str, tool_id: str, allow_write: bool = False) -> None: ...
    def list_bound_tools(self, agent_id: str) -> list[dict]: ...
    def save_tool_audit(self, audit: ToolAuditEvent) -> None: ...
    def list_tool_audits(self, agent_id: str, session_id: str | None = None) -> list[ToolAuditEvent]: ...
    def create_session(self, session: Session) -> None: ...
    def append_event(self, event: SessionEvent) -> None: ...
    def load_events(self, session_id: str) -> list[SessionEvent]: ...
    def iter_sessions(self): ...
    def list_agent_session_ids(self, agent_id: str) -> list[str]: ...
    def session_status(self, session_id: str) -> SessionStatus: ...
    def save_learning_run(self, run: LearningRun) -> None: ...
    def load_learning_run(self, run_id: str) -> LearningRun: ...
    def list_learning_runs(self, agent_id: str) -> list[LearningRun]: ...
    def save_learning_candidate(self, candidate: LearningCandidate) -> None: ...
    def load_learning_candidate(self, candidate_id: str) -> LearningCandidate: ...
    def list_learning_candidates(
        self,
        agent_id: str,
        state: PromotionState | None = None,
    ) -> list[LearningCandidate]: ...
    def save_validation_report(self, report: ValidationReport) -> None: ...
    def list_validation_reports(self, candidate_id: str) -> list[ValidationReport]: ...
    def save_gate_report(self, report: GateDecisionReport) -> None: ...
    def load_gate_report(self, report_id: str) -> GateDecisionReport: ...
    def list_gate_reports(self, candidate_id: str | None = None) -> list[GateDecisionReport]: ...
    def save_promotion_policy(self, policy: PromotionPolicy) -> None: ...
    def load_promotion_policy(self, agent_id: str) -> PromotionPolicy: ...
    def save_rollback_record(self, record: RollbackRecord) -> None: ...
    def list_rollback_records(self, candidate_id: str | None = None) -> list[RollbackRecord]: ...


class QueueStore(Protocol):
    def init(self) -> None: ...
    def enqueue(self, job: dict[str, Any]) -> None: ...
    def next_pending(self) -> dict[str, Any] | None: ...
    def mark_running(self, job: dict[str, Any]) -> None: ...
    def mark_completed(self, job: dict[str, Any]) -> None: ...
    def mark_failed(self, job: dict[str, Any], retry: bool) -> None: ...
    def depth(self) -> int: ...


class IdempotencyBackend(Protocol):
    def get(self, key: str) -> dict[str, Any] | None: ...
    def record(self, key: str, response_ref: dict[str, Any]) -> None: ...
